### ISSUE TITLE
AIP 2: Number of Votes per Account

### ISSUE THREAD

**Issue by Doweig** [ArkEcosystem/AIPs#1]
https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-2.md

TL DR: Number of Votes per Account to be `10`

Tell us what you think!

**Comment by 2mdoty** [comment]
Stay with Ark plan - no multiple voting with same Ark, Ark balance is split among multiple votes. Stake holders receive share of forging from pools, either as direct payment or equity in funded projects of delegates. Multiple voting allows cartels or large holders to take over network. If someone has enough interest in the project to buy enough Ark to unilaterally secure a delegate, he will also be motivated to secure and promote the project to increase the value of his holdings. The multiple voting amounts to an attempt at social engineering, and should be avoided.

**Comment by Doweig** [comment]
Ok, I heard you. Loud and clear ;)
Thanks for your feedback

**Comment by 2mdoty** [comment]
By using no multiple voting initially, we will have data from both ends of the spectrum to see how it works in practice. This will allow better prediction of results from a system somewhere in the middle, like what is proposed here. 

Sorry if I came off strongly in the earlier post. Thanks for setting up the AIP system. This is a much more organized and effective system to track proposed changes than doing it in Slack.

**Comment by Doweig** [comment]
No problem, strong opinion is better than no opinion 💃 
You are making a good point too, by going on the other end of the spectrum we will understand the mechanics better. A lot of this AIP is written on guessing and therefore not reliable. Let's stick to the original plan. I'll rewrite parts of the AIP to reflect the community consensus.

**Comment by 2mdoty** [comment]
Another option to explorer is ranked voting, where a multiplier is applied to votes based on order of preference, so if 10 votes were cast, the weight per vote might be 10x for 1st choice, 9X for second, down to 1X for 10th (last) choice. We will still want to establish a baseline with single voting, but a combination of multiple with ranked voting might produce optimal results, along with proxy voting.

**Comment by fix** [comment]
ok so far a simple implementation is 1 account - 1 vote. Several advantages:
- easy to move back to old voting system should we discover a weakness
- ultra fast processing (early test make it at least 2x as fast to process any transaction), so the network is supporting higher TPS

**Comment by dafty235** [comment]
I disagree with limiting accounts to n number of votes.

- The principal can't be tightly enforced.  If users were so inclined, they would create multiple accounts and split their voting weight across multiple delegates. Limiting an account to n number of votes is only a temporary obstacle. This makes this AIP inconsequential and would no doubt cause issues for users that insist on creating multiple accounts (managing multiple addresses, multiple passphrases, losing access to passphrases).

- It further promotes negative accumulation. Regular users will be aware that they can only cast limited votes with their account. The majority of users will seek to self-gain and spend their votes on pools. As the AIP mentions multiple times, voting for a pool does very little to benefit the network or the community - it only promotes self-growth (by increasing the voter's balance whenever pool payouts are made).

- There may be delegates that run projects or services that benefit the network and/or community, but are unable to offer any form of incentive to voters due to running costs or the sheer investment of resources to maintain a service. In turn, voters will not have an incentive to spend votes on these types of delegates, and the services themselves have no real incentive to continue operating.

- It may be damaging to revert once mainnet is launched. Active delegates won't be inclined to change the voting system once they are voted into a forging position because of the risk of being voted out. This could introduce a split between the community, with forging nodes who like the current system against non-forging nodes who don't.

- The current consensus seems to be that the older, split type voting was fairer and easier to use. The project and the community is in it's infancy. Imposing that community members can only vote for a limited number of other community members could be incredibly damaging for the project at this stage. As the AIP mentions, non-technical points need to also be considered.

- Is the latest implementation (1 account = 1 vote) going to be included as part of the initial mainnet release? I don't think the majority of the community are currently aware of this change.

**Comment by rrbest** [comment]
This is related but a bit of a modification to this proposal. It is called "Multiple Winner Ranked Choice Voting" and is very appropriate for any DPoS system. See here: http://www.fairvote.org/multi_winner_rcv_example

The method used by Lisk is known to be flawed, as described here (https://www.opavote.com/methods/traditional-plurality-voting#mntv) 

"Plurality at Large/Block Voting/MNTV
This method can be used to elect a council or committee. Suppose a committee of four is to be elected. Each voter selects up to four candidates, and the four candidates receiving the largest number of votes are the winners. This method is known as plurality at large voting, block (or bloc) voting, and the multiple non-transferable vote.

This is also not a good method for counting votes because it allows a majority of voters to control the entire committee. Suppose that a city is electing a council of 10 and that 51% of the city is party A and 49% is party B. Under this method, party A can elect its candidates to all 10 seats of the council and party B will be unrepresented even though it is supported by 49% of the voters."

Additional, to extend this, the existing method utilized by Ark is also known to be flawed. We are currently using a system called Single Non-transferable Vote.  https://en.wikipedia.org/wiki/Single_non-transferable_vote

Please read the section called "Potential for tactical voting" noting particularly the statement "The potential for tactical voting in a single non-transferable vote system is large. "

I propose exploring and possibly moving towards the multiple winner ranked-choice voting methodology.

**Comment by RobYocum** [comment]
After reviewing rrbest's proposal above, I agree that ranked-choice voting would be a large improvement. In today's system it is almost certainly a wasted vote to vote for anyone outside of the top 52 delegates. A ranked-choice system would allow you to vote for a non-forging delegate as your first choice but earn forged Ark with your second or third choice.  Your first-choice votes would lie in waiting until perhaps another person votes. This solves the issue we have today where it is very difficult to start a new pool because no one wants to vote for a non-forging deleage and wait until they (maybe) get enough votes.

Also, this proposal would make it very difficult for single-person ("whale") pools to be formed, which is undoubtedly better for the system. Under the current system, we have no way to remove a non-performing delegate that votes themselves in. The ranked-choice system could also more fairly distribute forged ark as votes would not get overly concentrated in a few delegates as they are now. 

I believe instituting this change would result in the best governance system possible for a dpos system.

**Comment by Jarunik** [comment]
I like the ranked choice system. If I understand it correctly it would also prevent "loosing shared profits" if your favorite candidate is not elected.  Your vote would automatically move to one candidate which is elected if you at least put one winning candidate on your voting list. This would allow a smoother entry for new delegates which still have to grow enough votes and prevent the lock in effect of being voted for because you are voted for and thus more likely to be able to share profit.

**Comment by rby123** [comment]
After reviewing rrbest's proposal above, I agree that ranked-choice voting would be a large improvement. In today's system it is almost certainly a wasted vote to vote for anyone outside of the top 52 delegates. A ranked-choice system would allow you to vote for a non-forging delegate as your first choice but earn forged Ark with your second or third choice. Your first-choice votes would lie in waiting until perhaps another person votes. This solves the issue we have today where it is very difficult to start a new pool because no one wants to vote for a non-forging deleage and wait until they (maybe) get enough votes.

Also, this proposal would make it very difficult for single-person ("whale") pools to be formed, which is undoubtedly better for the system. Under the current system, we have no way to remove a non-performing delegate that votes themselves in. The ranked-choice system could also more fairly distribute forged ark as votes would not get overly concentrated in a few delegates as they are now.

I believe instituting this change would result in the best governance system possible for a dpos system.

**Comment by fileninja** [comment]
I also agree with the ranked-Choice System. rrbest's linked articles are Good Points to See the actual upcoming Problems. As i Think Everything is said about that, i just Want to give a +1 from me.

**Comment by doubled1c3** [comment]
I know this AIP is old, but can be revived at any time and I'd like to have my thoughts here in case it does.

I don't agree with a Ranked Choice System. To be frank, I in fact strongly disagree that it would improve the governance model.  My dissent is aimed at the concept alone and not anyone personally or the original poster, so please keep in mind as reading.

I think it puts way too much psychological weight onto making sure you are receiving payouts as opposed to voting for the best delegates.  If you are voting for 1 delegate, and they drop out of forging, you are forced to assess whether you want to stick with them on merit, or select a delegate working harder for the community.  More importantly, you are doing this manually at the time the event occurs.  A lot of time may have passed from your initial vote, and the landscape may have changed.  Let's say you set up a list on month 1, consisting of del A and del B, and set it and forget it.  After 10 months, del A isn't doing what they promised and drops out of forging.  However, in that same time period, del B also isn't doing much of what they promised either.  But B is still forging.  Your votes automatically move to B without your involvement, when they would have been better served keeping a newer del in power who's working harder.  At the time you set up the list, everything seemed fine, but the ranking system further reduces your need to "check up on things" and participate in the governance model. People are lazy.  But if you force them to reassess their position at that moment, it becomes more convenient for them to learn of the current delegate landscape and make a new choice based on that, not based on an autolist they set up in the past.

I heard "In today's system it is almost certainly a wasted vote to vote for anyone outside of the top 52 delegates." Wow, no. In today's system there aren't enough delegates actively trying to get into top 51. There are also not enough human voters. That's not the system's fault... if you had 200 delegates scrambling to be in top 51 and 800,000 voters those outside votes would become critical, showing support for the delegate based on merit. I'm talking about activity, daily Slack chats, articles, videos, community involvement.  Delegates outside the top 51 who get into the 51 all start with "wasted votes" which tell the entire network that some people believe in the del so much they are willing to not get paid in order to show their support, which begets more support in turn. This is how a del organically rises to power.  This is part of the intrinsic beauty of the system.

The RCS would probably prevent nonforgers from entering the 51.  Say I am voting for a forging delegate, but I really like this #54 del and what they stand for, so I will put him on my list.  Well, say a whole lot of people do this.  Now, you've got a forging del with say 1.5 million votes, and a standby del with 10 million pretend votes (ranked choice list entries).  #54 has magnitudes **more support**, but everyone is waiting for their first choice to drop out.  In that case, who truly deserves to be forging? The RCS takes away priority from people putting their money where their mouth is and actually voting for a non51 they believe in. 

In the current system, as non51 votes go up, forging votes go down.  This is the beauty of the current system.  A wildcard del enters the arena, and literally takes votes away from forgers to rise into power.  The resulting chaos forces dropping forgers to appeal to the community.  This is the way it's supposed to be.  There's nothing I love more than watching a desperate forger who has been sitting around for a year doing nothing for Ark, spamming Slack as hard as they can begging for votes because a new wildcard Ark activist showed up and took away a critical mass of their votes.  With the RCS, this new wildcard del would simply be put on a "list of interest" below a bunch of forgers who are now perfectly safe from chaos.

Moreover, the RCS would immediately and catastrophically punish anyone who dropped out of forging even for a moment. In the current system, if delegate is fine and people are happy, but they drop out of forging for a moment, no problem, people stay supporting, votes are regained, forging resumes.  The RCS would immediately strip away all votes from this delegate, and they would have to start again from zero working against the very steep hill the RCS has created, as explained earlier.

Granted, this AIP is over a year old and people may not feel in support of the RCS today, but these comments were important for me to contribute, to participate in the democratic aspect of Ark.  Thank you very much for listening and I appreciate all the hard work Ark contributors are doing.  Thank you again. And if I'm misunderstanding anything about the RCS please explain the mechanics further and I will reassess that, but may want to let me know on Slack a reply was made so I can take a look.

**Comment by rrbest** [comment]
Nobody waits for their first choice to drop out, by definition everyone wants their first choice to stay forging. Realistically, if in your example someone had 10 million 2nd place votes, its almost certain that extra votes would be allocated to that candidate and they would forge. One might wonder why this candidate is nobody's first choice. Remember, you can have this candidate as your first choice and if they don't collect enough votes to forge, your votes get allocated elsewhere. Similarly, if everyone votes for other candidates and they collectively have too many votes, those extras get allocated to Del 2, and they may get enough extra votes to forge as well. 

RCS never punished anyone for falling out, and recovering is much easier than collecting a million votes again. It is much more catastrophic to fall out of forging in the current system as voters desperately try to avoid losing forging rewards. Typically, a voter will go vote for a profit sharing pool until the delegate has secure votes elsewhere. This is not very efficient. If the delegate cant get votes fast enough, they may go cold. RCS solves this as well. 

I do think you may have some misunderstanding of what ranked choice voting is. Here is a good resource http://www.fairvote.org/rcv#how_rcv_works

**Comment by doubled1c3** [comment]
Oh hi, I hadn't noticed you responded.  So I have read your response here, and it seems there are 2 conflicting concepts happening at once... let me set up a series of premises and see your response.

1. RCS has ability to accept a list of delegates from a wallet, ranked most important to the voter to least important to the voter.

2. RCS can only allocate all Ark to 1 del on list, RCS can't float some Arks here some there.

3. RCS primary directive is to vote for the highest delegate on the voter's list that is currently forging right now. RCS primary directive is to maintain forging at all times.

4. RCS has ability to unvote and revote by itself.

5. So Joe has a list of del A, B, and C.  Del A is not forging, so RCS is voting for del B and Joe is receiving rewards from B.

6. RCS eventually notices(?) that a bunch of people have del A as their higher choice, similar to Joe, but A is not forging. RCS understands that if it mass unrevotes a bunch of wallets, A will forge.

7.  RCS executes this.  Joe smoothly transitions from voting for del B to A, and rewards are good to go.

8. Because RCS executes the unrevote at the precise moment of critical mass, there is no vote surplus for A, they move into the exact slot 51. So this is fine.

9. Things seem fine, and B is still forging also, but the RCS unrevoting has now caused del C to drop from forging.

10. RCS searches for del C in lists that are a higher priority than current forging del in those lists.

11. RCS finds a bunch of standby votes in a bunch of lists, but ignores them because there are delegates higher up in those lists that are forging. To be more specific, RCS will unvote slot #2 in order to put slot #1 in forging, so long as critical mass is hit for forging as explained earlier.  But slot #1 will never unvote to vote for slot #2, because the priority is backwards.

12. A) So delegate C is dropped from forging, and there are no votes recorded on their delegate because RCS has routed all their votes away the second they stopped forging.  RCS primary directive is to maintain forging rewards at all times. So if delegate C drops from forging by 1 Arkvote, RCS does not retrieve the Arkvotes to retain forging from a different wallet with high ranking on C.  Instead it abandons all votes for del C.

I guess that's the source of the two concepts confusion.  If a delegate drops out of forging, does RCS try to retain their forging by reallocating votes based on priority in lists, or does it revote all wallets away from the delegate to retain forging rewards? These concepts seem to be opposite

**Comment by rrbest** [comment]
I think the difficulty is coming from the idea that RCS is not done iteratively, but at the time of election. RCS allows users to rank their candidates, and then the RCV algorithm uses everyones ranking and vote weighting to determine which 51 delegates to elect to that round to maximize happiness. You are either elected or not, and no votes are wasted. if you did not win the election, this doesn't mean you go cold. It is possible you could be elected the next round if someone changed their rankings. Recall what a round is in voting. It's essentially an election cycle where 51 delegates forge blocks. When the 51 delegates have forged, we select a new group of delegates to forge. We can either do this with simple 1 ark 1 vote, top 51 delegates are elected, or we can use ranked choice voting to ensure that no votes are 'cold' or wasted.
