### ISSUE TITLE
AIP 27: Addressing Long Range Attacks - Discussion

### ISSUE THREAD

**Issue by moazzamak** [ArkEcosystem/AIPs#45]
Discussion for: [AIP 27](https://github.com/ArkEcosystem/AIPs/blob/master/AIPS/aip-27.md)

Chris asked that I should separate the long range attack additions that were created for AIP 25 as a result of the open discussion should be made into a new separate AIP so here it is. Let me know your thoughts.

**Comment by kristjank** [comment]
mak [22:50]
Hi everyone, After discussions regarding the AIP 25 I tried to come up with some ideas that might help us prevent long range attacks in a (D)PoS network. I would like to get your feedback and critique on the topic: Link to discussion is https://github.com/ArkEcosystem/AIPs/issues/45
GitHub
AIP 27: Addressing Long Range Attacks - Discussion · Issue #45 · ArkEcosystem/AIPs
Discussion for: AIP 27 Chris asked that I should separate the long range attack additions that were created for AIP 25 as a result of the open discussion should be made into a new separate AIP so h...

Moon (biz_network) [22:55]
Those all generally suffer from weak subjectivity. Also because probability is literally just that - probability - rejecting potentially legitimate chains in the case that you are on the orphan chain will end up downing your node until you manually rebuild to the actual highest chain (at which point you will accept a Sybil'd LRA chain anyway).
@mak
Basically those are both weak solutions that other chains have considered and those who go with them still have the weak subjectivity issue and new nodes coming online as well as clients are vulnerable to Sybil attacks, at which point you end up centralizing your chain to trusted nodes, killing the point of the chain in the first place.
PoW has not been solved yet :grin:

mak [22:57]
that's a valid point. Though that's why I include a "trust" parameter that each delegate builds over time for their own chain.
I don't know how to solve the sybil attack scenario yet

Moon (biz_network) [22:58]
But your individual node is only relevant when the majority of nodes run trusted code. That's the point. You can't just say "lol ignore Sybil attacks" because it's not only easy to do one but it's the fastest and most effective way of wrecking a non-PoW network.
You can't just pretend PoS' biggest problem doesn't exist lol

mak [22:58]
but quite frankly that's an issue even in the current network
and affects exchanges and users

Moon (biz_network) [22:59]
PoW doesn't suffer from Sybil attacks because you only need to be fed the honest chain from one node. You don't have to trust that node. The client can do all the verification on its own. Can't do the same with (D)PoS which is the fundamental problem nobody has been able to solve.

mak [22:59]
I'm not ignoring sybil attacks. Just saying I don't know how to solve them yet and will spend some time looking into it later.

Moon (biz_network) [22:59]
I know. I'm saying attacking the problem WITHOUT considering Sybil attacks is irrelevant.
Because all attack vectors for PoS are propagated via Sybil attacks.
And Sybil attacks cannot be mitigated with PoS. At the end of the day that is the ultimate problem that needs solving.
With PoW one honest node proves the other are dishonest. PoS has no possible way to do that.

mak [23:01]
I'm not giving up on that yet
I think the issue of Sybil attacks is above the concensus layer

Moon (biz_network) [23:02]
It doesn't matter though because you can't prevent them

mak [23:02]
and therefore we should be looking at solving it above the concensus layer

Moon (biz_network) [23:02]
Don't think so

mak [23:02]
via creating the right incentive structure

Moon (biz_network) [23:02]
You need to assume that your network is always Sybil'd

mak [23:02]
that discourages sybil attacks

Moon (biz_network) [23:02]
There's no such thing though
How can you discourage taking over the network and controlling it economically?

mak [23:02]
i.e PoW discourages sybil attacks via sunk cost due to mining power bills

Moon (biz_network) [23:03]
Sybil attacks have nothing to do with mining
They're free on BTC too.
"free" as in negligible
The reason they don't work has nothing to do with cost

mak [23:03]
not quite. like you said one honest node can prove all dishonest nodes wrong in PoW

Moon (biz_network) [23:04]
You can indeed sybil BTC but it will not lend you any financial gain because you can't overwrite the chain with a Sybil attack
In order to make that true on PoS you literally need a PROOF that your chain is better, and WORK is the only tangible thing that can do that.

mak [23:04]
with AIP25+27 you can't rewrite the honest chain either

Moon (biz_network) [23:04]
You can

mak [23:04]
the problem is at exchange and customers end

Moon (biz_network) [23:04]
LRA wrecks you.
I've been brainstorming a solution for years now and the only reasonable solution I came up with  is a hybrid system.
It functions with a very low PoW as long as one delegate remains honest.

Jarunik [23:05]
the fundamental problem is that you have no proof like the POW difficulty ... so you got nothing unfakable in dpos

Moon (biz_network) [23:06]
It's very power efficient and still DPoS. My solution is still technically PoW but it reduces the effectiveness of hash attacks by a factor of 50x
But pure (D)PoS cannot solve the problem. Again, if you solve it you will literally become a millionaire and Vitalik will personally be your date to the ball.

Jarunik [23:06]
to solve it differently then POW you would have to find something that proofs that it took you time to create a block (whitout the possiblity to fake timestamps and such) (edited) 

Moon (biz_network) [23:07]
And if it takes time it means someone can use more power instead of time than you to overtake it
There's no such thing as real timestamps though :slightly_smiling_face: @Jarunik
You can only prove that one thing happened before something else

Jarunik [23:07]
yeah that is what i want to say

Moon (biz_network) [23:07]
You can't prove it happened at an exact date

Jarunik [23:07]
there is not "time" in the logical equation
as you can't proof time
well at least not directly
doh ... you know what i mean

Moon (biz_network) [23:08]
I'm happy to discuss ideas on it since this is the area I am most interested in when it comes to blockchains. But in all my research there has been nothing even remotely close that could solve the PoW problem. @mak
The best I could get is a hybrid system that leverages the strengths of both.
And only requires honest nodes to have 1/50th of the hashpower of dishonest ones

mak [23:09]
anyways. I'm still going to be spending time trying to figure out if sybil resistance can be developed without PoW

Moon (biz_network) [23:09]
(So 51% attacks must be 99% attacks and you must own a delegate)

mak [23:09]
I understand your points

Jarunik [23:10]
maybe votes should need POW ^^

mak [23:10]
but my point is that even though we can't completely stop sybil attacks if we can make it expensive enough it would serve as a good deterrent

Moon (biz_network) [23:10]
Then you give people another attack vector @Jarunik
Votes don't do any sort of consensus so it doesn't do much
@mak You can't though because no amount of banning matters when MY fake nodes are more than your real ones.
My nodes don't adhere to your software rules
And normal nodes accept my perfectly valid chain blocks
BTC can still be Sybil'd. It is not protected from Sybil attacks
It is protected from FINANCIAL damage from Sybil attacks
But it would be relatively trivial to actually Sybil Bitcoin

Jarunik [23:12]
i think there will never be a "true identity" that can be proofen ... so you can always create sybil attacks

Moon (biz_network) [23:12]
Exactly

mak [23:12]
and that's exactly what we need for DPoS

Moon (biz_network) [23:12]
That doesn't exist lol

mak [23:13]
I mean no financial damage

Moon (biz_network) [23:13]
Yeah you can't

mak [23:13]
as a result of sybil attacks

Moon (biz_network) [23:13]
But you cannot stop them, even in PoW
So you have to work around the assumption that the network can always be sybil'd
BTC doesn't fail in a Sybil attack
All (D)PoS does in combination with LRA
Whatever solution you want MUST work when any normal node can find the right chain from 0 without trusting others.
That solution exists for PoW, but not for any PoS system (edited) 

Jarunik [23:14]
in POW you find it because you can check with which difficulty the block was mined ... so you can pick the longest ... correct?

Moon (biz_network) [23:14]
Correct
That's why 51% attacks work
Sorry let me correct
Not which difficulty, but longest chain of work
They are not technically the same thing, but you get the idea
The most total work in the chain is the valid chain

Jarunik [23:16]
yeah as blocks with right/highest difficulty took most work

Moon (biz_network) [23:16]
Not always
Difficulty can drop

Jarunik [23:16]
ah yeah ... :slightly_smiling_face:

Moon (biz_network) [23:16]
That's why you use total work
Which is basically a formula that is essentially the sum of each block's difficulty for the entire chain
It's not *exactly* that but that's the general idea

Jarunik [23:18]
if you could deduct from the existing chain which delegate forged the next block then it would work ... but unfortunately that is not possible as delegates can miss the blocks (edited) 

Moon (biz_network) [23:19]
wdym?

Jarunik [23:19]
so if you just follow the "next delegate that should forge" then you would end in some fake branch.

Moon (biz_network) [23:20]
That doesn't stop attacks though. Even if there are zero missed blocks I could make a chain that is always one block ahead of yours.

Jarunik [23:20]
so even finding a way to ensure that it is proofen who is the next delegate (i understood that is was mak tries to do) won't help

Moon (biz_network) [23:20]
The problem with proving the next delegate is the LRA problem
Which anybody can do on ARK right now
(Thanks Axi)

Jarunik [23:21]
yeah .... you just add your block with axi in some "fork" and create your own chain on it

Moon (biz_network) [23:21]
Yep, and you control every delegate on that fork

Jarunik [23:21]
then you just swap it out with a sybill

Moon (biz_network) [23:21]
So you catch up to the real chain
then Sybil for propagation
That's why I'm going with hybrid DPoS+PoW
Using something like MimbleWimble for the PoW
But I know ARK wants to remain pure DPoS

zillion [23:23]
Can't we just ban Axi public key? (edited) 

Moon (biz_network) [23:23]
Nope
You'll end up banning his blocks on the real chain
You could except every one of his blocks up until now
But then you are LITERALLY hardcoding the blockchain into the code
:trollface:

zillion [23:24]
Well after some height

Moon (biz_network) [23:24]
Doesn't work because LRAs will be before any height you choose @zillion

Jarunik [23:24]
and what with all the other private keys of every delegate that ever forged?

Moon (biz_network) [23:24]
And after that height I'll have 51 other delegates
@Jarunik Any delegate can LRA the chain basically

Jarunik [23:24]
yes

Moon (biz_network) [23:24]
Within just a few blocks
Thanks to :drum_with_drumsticks:
NO NONCES!

spghtz (ark.party / civseed) [23:37]
why not just do checkpoints?

Moon (biz_network) [23:38]
That's the only solution but technically still a bandaid.

spghtz (ark.party / civseed) [23:38]
yea

Moon (biz_network) [23:39]
Checkpoints won't solve LRA attacks starting from the checkpoint though by any delegate.
Since any delegate at any checkpoint can overtake the chain in just a few blocks at any time

spghtz (ark.party / civseed) [23:39]
right

Jarunik [23:40]
checkpoints would be what to verify the history ?

Moon (biz_network) [23:40]
Checkpoints would be hardcoded block ids
Set back n blocks and pushed through client updates

spghtz (ark.party / civseed) [23:40]
you could add a checkpoint everytime there is a change in delegate order :hyperxd:

Jarunik [23:40]
no thanks ^^

Moon (biz_network) [23:40]
Can't because they'd be hardcoded in the client
Otherwise you are trusting the delegates running the chain again or introducing weak subjectivity again through another method
And that makes it no better than setting a limit on how far back you can accept blocks, which would again suffer from LRA + Sybil memes

Jarunik [23:42]
and your hybrid would create some pow blocks in between ?

Moon (biz_network) [23:42]
No
Much simpler and much easier
Delegates accept PoW hashes at a difficulty and those hashes are seeded by the block right before the start of the round
So the hashes are valid for 51 (or 101) blocks
And they're used as PoW
1 hash is as valid as 1 delegate signature
So a round has 51 delegate signatures and 51 PoW hashes on average

Jarunik [23:43]
ah ... so very low difficulty that the delegates can solve within the round

Moon (biz_network) [23:43]
Not delegates, miners
You still want substantial PoW power
Otherwise you can get 99% attacked easily using one delegate
Longest chain = most "chain proof"

Jarunik [23:44]
why do you need delegates still then?

Moon (biz_network) [23:45]
Each delegate signature in a round counts towards chain proof
single_delegate_Signature = total_pow_this_round / 51
Delegates are the ones committing the PoW hashes, sort of like pools

Jarunik [23:46]
ah ... so delegates kind of "channel" the miners results into blocks

Moon (biz_network) [23:47]
Yes, but delegate signatures also count equally towards the proof

Jarunik [23:47]
so you could also have just 1 miner

Moon (biz_network) [23:47]
So 51 delegates signing a round count as much as all the hashes
So round "chain work" is always 2n where n is the total work of the miners
This means to overtake a chain with 50 honest delegates you'd need 1 bad delegate and 50.1x the hashrate of the honest miners, instead of 1.1x in traditional PoW.
And vice versa if you control 50 bad delegates, if all miners migrate to the honest chain, just 1 delegate can take back the chain
You need to 51% both the PoW and the PoS systems to overtake the chain

Jarunik [23:48]
and rewards are split to miners and delegates accordingly i assume

Moon (biz_network) [23:48]
Yeah

Jarunik [23:49]
what happens if there is no miner ?

Moon (biz_network) [23:49]
Bad things ofc
1 bad delegate could overtake the chain

Jarunik [23:49]
would it just run like current dpos?

Moon (biz_network) [23:49]
Until a bad delegate comes along yeah
But this system only needs 2% of the PoW of normal PoW systems to remain secure
And scales depending on how many delegates collude to harm the network
Miners keep the delegates honest and delegates keep the miners honest

Jarunik [23:50]
unless delegates are miners too :wink:

Moon (biz_network) [23:50]
Nothing wrong with that, they still need the power
1 bad delegate needs 50x the hashrate
2 bad delegates need 25x
etc
hashes remain valid for the whole round and not just a block like traditonal PoW because if a delegate goes bad and rejects hashes you still want them to be valid so they can contribute to network security

Jarunik [23:52]
interesting ... but also complicated ^^

Moon (biz_network) [23:52]
PoW here does nothing but serves to augment the broken PoS system
Because I've accepted that you cannot solve LRA attacks (yet) :stuck_out_tongue: (edited) 
and "weak subjectivity" is just another way of saying centralization

Jarunik [23:55]
thanks for explaining

**Comment by moazzamak** [comment]
Slack log for discussion:

> Moon (biz_network) [10:55 PM]
> Those all generally suffer from weak subjectivity. Also because probability is literally just that - probability - rejecting potentially legitimate chains in the case that you are on the orphan chain will end up downing your node until you manually rebuild to the actual highest chain (at which point you will accept a Sybil'd LRA chain anyway).
> @mak
> Basically those are both weak solutions that other chains have considered and those who go with them still have the weak subjectivity issue and new nodes coming online as well as clients are vulnerable to Sybil attacks, at which point you end up centralizing your chain to trusted nodes, killing the point of the chain in the first place.
> PoW has not been solved yet :grin:
> 
> 
> mak [10:57 PM]
> that's a valid point. Though that's why I include a "trust" parameter that each delegate builds over time for their own chain.
> I don't know how to solve the sybil attack scenario yet
> 
> Moon (biz_network) [10:58 PM]
> But your individual node is only relevant when the majority of nodes run trusted code. That's the point. You can't just say "lol ignore Sybil attacks" because it's not only easy to do one but it's the fastest and most effective way of wrecking a non-PoW network.
> You can't just pretend PoS' biggest problem doesn't exist lol
> 
> mak [10:58 PM]
> but quite frankly that's an issue even in the current network
> and affects exchanges and users
> 
> Moon (biz_network) [10:59 PM]
> PoW doesn't suffer from Sybil attacks because you only need to be fed the honest chain from one node. You don't have to trust that node. The client can do all the verification on its own. Can't do the same with (D)PoS which is the fundamental problem nobody has been able to solve.
> 
> mak [10:59 PM]
> I'm not ignoring sybil attacks. Just saying I don't know how to solve them yet and will spend some time looking into it later.
> 
> Moon (biz_network) [10:59 PM]
> I know. I'm saying attacking the problem WITHOUT considering Sybil attacks is irrelevant.
> Because all attack vectors for PoS are propagated via Sybil attacks.
> And Sybil attacks cannot be mitigated with PoS. At the end of the day that is the ultimate problem that needs solving.
> With PoW one honest node proves the other are dishonest. PoS has no possible way to do that.
> 
> mak [11:01 PM]
> I'm not giving up on that yet
> I think the issue of Sybil attacks is above the concensus layer
> 
> Moon (biz_network) [11:02 PM]
> It doesn't matter though because you can't prevent them
> 
> mak [11:02 PM]
> and therefore we should be looking at solving it above the concensus layer
> 
> Moon (biz_network) [11:02 PM]
> Don't think so
> 
> mak [11:02 PM]
> via creating the right incentive structure
> 
> Moon (biz_network) [11:02 PM]
> You need to assume that your network is always Sybil'd
> 
> mak [11:02 PM]
> that discourages sybil attacks
> 
> Moon (biz_network) [11:02 PM]
> There's no such thing though
> How can you discourage taking over the network and controlling it economically?
> 
> mak [11:02 PM]
> i.e PoW discourages sybil attacks via sunk cost due to mining power bills
> 
> Moon (biz_network) [11:03 PM]
> Sybil attacks have nothing to do with mining
> They're free on BTC too.
> "free" as in negligible
> The reason they don't work has nothing to do with cost
> 
> mak [11:03 PM]
> not quite. like you said one honest node can prove all dishonest nodes wrong in PoW
> 
> Moon (biz_network) [11:04 PM]
> You can indeed sybil BTC but it will not lend you any financial gain because you can't overwrite the chain with a Sybil attack
> In order to make that true on PoS you literally need a PROOF that your chain is better, and WORK is the only tangible thing that can do that.
> 
> mak [11:04 PM]
> with AIP25+27 you can't rewrite the honest chain either
> 
> Moon (biz_network) [11:04 PM]
> You can
> 
> mak [11:04 PM]
> the problem is at exchange and customers end
> 
> Moon (biz_network) [11:04 PM]
> LRA wrecks you.
> I've been brainstorming a solution for years now and the only reasonable solution I came up with  is a hybrid system.
> It functions with a very low PoW as long as one delegate remains honest.
> 
> Jarunik [11:05 PM]
> the fundamental problem is that you have no proof like the POW difficulty ... so you got nothing unfakable in dpos
> 
> Moon (biz_network) [11:06 PM]
> It's very power efficient and still DPoS. My solution is still technically PoW but it reduces the effectiveness of hash attacks by a factor of 50x
> But pure (D)PoS cannot solve the problem. Again, if you solve it you will literally become a millionaire and Vitalik will personally be your date to the ball.
> 
> Jarunik [11:06 PM]
> to solve it differently then POW you would have to find something that proofs that it took you time to create a block (whitout the possiblity to fake timestamps and such) (edited) 
> 
> Moon (biz_network) [11:07 PM]
> And if it takes time it means someone can use more power instead of time than you to overtake it
> There's no such thing as real timestamps though :slightly_smiling_face: @Jarunik
> You can only prove that one thing happened before something else
> 
> Jarunik [11:07 PM]
> yeah that is what i want to say
> 
> Moon (biz_network) [11:07 PM]
> You can't prove it happened at an exact date
> 
> Jarunik [11:07 PM]
> there is not "time" in the logical equation
> as you can't proof time
> well at least not directly
> doh ... you know what i mean
> 
> Moon (biz_network) [11:08 PM]
> I'm happy to discuss ideas on it since this is the area I am most interested in when it comes to blockchains. But in all my research there has been nothing even remotely close that could solve the PoW problem. @mak
> The best I could get is a hybrid system that leverages the strengths of both.
> And only requires honest nodes to have 1/50th of the hashpower of dishonest ones
> 
> mak [11:09 PM]
> anyways. I'm still going to be spending time trying to figure out if sybil resistance can be developed without PoW
> 
> Moon (biz_network) [11:09 PM]
> (So 51% attacks must be 99% attacks and you must own a delegate)
> 
> mak [11:09 PM]
> I understand your points
> 
> Jarunik [11:10 PM]
> maybe votes should need POW ^^
> 
> mak [11:10 PM]
> but my point is that even though we can't completely stop sybil attacks if we can make it expensive enough it would serve as a good deterrent
> 
> Moon (biz_network) [11:10 PM]
> Then you give people another attack vector @Jarunik
> Votes don't do any sort of consensus so it doesn't do much
> @mak You can't though because no amount of banning matters when MY fake nodes are more than your real ones.
> My nodes don't adhere to your software rules
> And normal nodes accept my perfectly valid chain blocks
> BTC can still be Sybil'd. It is not protected from Sybil attacks
> It is protected from FINANCIAL damage from Sybil attacks
> But it would be relatively trivial to actually Sybil Bitcoin
> 
> Jarunik [11:12 PM]
> i think there will never be a "true identity" that can be proofen ... so you can always create sybil attacks
> 
> Moon (biz_network) [11:12 PM]
> Exactly
> 
> mak [11:12 PM]
> and that's exactly what we need for DPoS
> 
> Moon (biz_network) [11:12 PM]
> That doesn't exist lol
> 
> mak [11:13 PM]
> I mean no financial damage
> 
> Moon (biz_network) [11:13 PM]
> Yeah you can't
> 
> mak [11:13 PM]
> as a result of sybil attacks
> 
> Moon (biz_network) [11:13 PM]
> But you cannot stop them, even in PoW
> So you have to work around the assumption that the network can always be sybil'd
> BTC doesn't fail in a Sybil attack
> All (D)PoS does in combination with LRA
> Whatever solution you want MUST work when any normal node can find the right chain from 0 without trusting others.
> That solution exists for PoW, but not for any PoS system (edited)

**Comment by moazzamak** [comment]
I just realized that if the AIP23 is implemented then the cost of executing a sybil attack is increased significantly because every delegate registered on the Ark main chain's delegate market would be acting as a relay. So as the ecosystem grows and more chains are added and assigned a token value the number of delegates would also increase and therefore the cost of carrying out a sybil attack on main chain as well. As for bridge chains using the delegate markets they can add checkpoints into main chain using liquidity gates to secure themselves.

**Comment by Jarunik** [comment]
My summary for more light weight check points which would also address LRA.

We should discuss how to reduce the potential harm of long range attacks.
Some regular checkpoints of blocks that are hard-coded in the client could shorten the window of long range attacks to the time frame between the last checkpoint and now.
As checkpoints would most likely have to be included in the core code they would create more centralisation.
We will not solve weak subjectivity. But a more transparent way to agree on the history through checkpoints might be beneficial.

**Comment by kakukimote** [comment]
mk
